---
- name: Distributing file to datanodes
  command:  su - {{ hadoop_user }} -c 'rsync -avzp -e "ssh -o StrictHostKeyChecking=no" /tmp/{{ hadoop_download_url | basename }} {{ inventory_hostname }}:/tmp/{{ hadoop_download_url | basename }}'
  delegate_to: nn

- name: Run tasks from namenode role 
  include_role:
    name: hadoop-namenode
    tasks_from: hadoop-common
   

