---
- name: Installing base packages
  yum: name={{ packages}} state=present

- name: adding hadoopadmin user
  user: 
     name: "{{ hadoop_user }}"

- name: Generate /etc/hosts file
  template:
    src: hosts.j2
    dest: /etc/hosts
