---
- hosts: all
  become: yes
  gather_facts: yes
  roles:
  - role: lvm
    disk: "/dev/sdb"
  - role: common
  - role: java

- hosts: namenode
  become: yes
  gather_facts: no
  roles:
  - role: hadoop-namenode

- hosts: datanodes
  become: yes
  gather_facts: no
  roles:
  - role: hadoop-datanodes
